version: "3.4"

services:
  aspnetcorewebapi:
    image: ${DOCKER_REGISTRY-}aspnetcorewebapi
    container_name: aspnetcorewebapi
    build:
      context: .
      dockerfile: ASPNETCoreWebAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=anasoft
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
    depends_on:
      - "postgres-db"
      - "rabbitmq-server"

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: NewsAndMedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data

  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db_volume:
